version: '3'
services:
  memgraph:
    image: "memgraph"
    ports:
      - "7687:7687"
  memcached:
    image: memcached:latest
    ports:
      - "11211:11211"
  simulator:
    build: ./simulator
    volumes:
      - ./simulator:/app
    ports:
      - "3000:3000"
    environment:
      MG_HOST: memgraph
      MG_PORT: 7687
    command: /wait-for-it.sh memgraph:7687 -- python main.py start nm
    depends_on:
      - memgraph
  web:
    build: ./web_app
    volumes:
      - ./web_app:/app
    ports:
      - "8000:8000"
    environment:
      MG_HOST: memgraph
      MG_PORT: 7687
      MC_HOST: memcached
      MC_PORT: 11211
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - simulator