#For connectiong to a remote Memgraph DB instance

version: '3'
services:
#  memgraph:
#    image: "memgraph"
#    ports:
#      - "7687:7687"
  simulator:
    build: ./simulator
    volumes:
      - ./simulator:/app
    ports:
      - "3000:3000"
    environment:
      MG_HOST: "34.248.115.177"
      MG_PORT: 9000
      MG_USERNAME: "userWrite"
      MG_PASSWORD: "starwriteitlink91$$2"
      TLE_FILE_PATH: "imports/tle_3"
      CITIES_FILE_PATH: "imports/cities.csv"
      DB_UPDATE_TIME: 0.2
      EDGE_ORBITS_CONNECTED: 'false'
      ORBIT_ENDS_CONNECTED: 'false'
      SAT_PROCESSING_DELAY: 0.010
      RELAY_PROCESSING_DELAY: 0.012 
      VIEW_ANGLE: 70
    command: python main.py start
#    command: /wait-for-it.sh memgraph:7687 -- python main.py start
#    depends_on:
#      - memgraph
  web:
    build: ./web_app
    volumes:
      - ./web_app:/app
    ports:
      - "5000:5000"
    environment:
      MG_HOST: "34.248.115.177"
      MG_PORT: 9000
      MG_USERNAME: "userReadonly"
      MG_PASSWORD: "starlinkreadit"
      OPTICAL_FILE_PATH: "resources/latencies.csv"
    depends_on:
      - simulator
  redis:
    image: "redis"
    ports:
        - 6379:6379
  cache_handler:
    build:
      context: ./cache_handler
    volumes: 
      - ./cache_handler:/app
    environment:
      MG_HOST: memgraph
      MG_PORT: 7687
      REDIS_HOST: redis
      REDIS_PORT: "6379"
      REDIS_PASSWORD: ""
      DB_FETCH_TIME: "0.1"
    command: python cache_handler.py
    depends_on:
      - redis
      - memgraph