version: '3'
services:
  memgraph:
    image: "memgraph"
    ports:
      - "7687:7687"
  memcached:
    image: memcached:latest
    ports:
      - "11211:11211"
  simulator:
    build: ./simulator
    volumes:
      - ./simulator:/app
    ports:
      - "3000:3000"
    environment:
      MG_HOST: memgraph
      MG_PORT: 7687
      TLE_FILE_PATH: "imports/tle_3"
      CITIES_FILE_PATH: "imports/cities.csv"
      DB_UPDATE_TIME: 0
      EDGE_ORBITS_CONNECTED: 'false'
      ORBIT_ENDS_CONNECTED: 'false'
      SAT_PROCESSING_DELAY: 0.004
      RELAY_PROCESSING_DELAY: 0.008 
      VIEW_ANGLE: 70
    command: /wait-for-it.sh memgraph:7687 -- python main.py start
    depends_on:
      - memgraph
  web:
    build: ./web_app
    volumes:
      - ./web_app:/app
    ports:
      - "8000:8000"
    environment:
      MG_HOST: memgraph
      MG_PORT: 7687
      MC_HOST: memcached
      MC_PORT: 11211
    #command: bash -c "python manage.py collectstatic && python manage.py runserver 0.0.0.0:8000"
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - simulator