version: '3'
services:
  memgraph:
    image: "memgraph"
    ports:
      - "7687:7687"
  simulator:
    build: ./simulator
    volumes:
      - ./simulator:/app
    ports:
      - "3000:3000"
    environment:
      MG_HOST: memgraph
      MG_PORT: 7687
    command: python main.py start nm
    depends_on:
      - memgraph
  web:
    build: ./web_app
    volumes:
      - ./web_app:/app
    ports:
      - "8000:8000"
    environment:
      MG_HOST: memgraph
      MG_PORT: 7687
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - simulator