[tool.poetry]
name = "data_handler"
version = "0.1.0"
description = ""
authors = []

[tool.poetry.dependencies]
python = "^3.7"
pymgclient = "^0.1.0"
redis = "^3.5.3"
neo4j = "^1.7.4"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
